apiVersion: v1
kind: Service
metadata:
  name: traindetailservice
  labels:
    run: traindetailservice
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: traindetailservice